### ISSUE TITLE
not compatible with original minizip

### ISSUE THREAD

**Issue by MakarenkoPavel** [nmoinvaz/minizip#405]
there is no support for:
- zipOpenNewFileInZip function
- uLong type
- some #define flags like Z_DEFLATED, Z_DEFAULT_COMPRESSION

all this things provided by original minizip 1.1 with  zlib 1.2.11 and included by "zip.h", "unzip.h" headers

**Comment by Coeur** [comment]
It would have been minizip 1.3 instead of 2.0 if there had been no breaking changes. ;)

- If you take a look at mz_compat.c, you'll find out that `zipOpenNewFileInZip` has been replaced with `mz_zip_entry_write_open`.

- uLong was part of zlib.h, which is now an optional dependency. (you may do `typedef unsigned long int uLong;` if you miss it)

- Z_DEFLATED and Z_DEFAULT_COMPRESSION have been replaced by parameter `int16_t compress_level`.

**Comment by nmoinvaz** [comment]
- The dev branch contains the missing function `zipOpenNewFileInZip`.
- `uLong`, `Z_DEFLATED`, and `Z_DEFAULT_COMPRESSION` are part of zlib, not part of minizip.

**Comment by Coeur** [comment]
Oh, true, I missed #400 ah ah.

**Comment by MakarenkoPavel** [comment]
> It would have been minizip 1.3 instead of 2.0 if there had been no breaking changes. ;)
> 
> * If you take a look at mz_compat.c, you'll find out that `zipOpenNewFileInZip` has been replaced with `mz_zip_entry_write_open`.
> * uLong was part of zlib.h, which is now an optional dependency. (you may do `typedef unsigned long int uLong;` if you miss it)
> * Z_DEFLATED and Z_DEFAULT_COMPRESSION have been replaced by parameter `int16_t compress_level`.

I think you should find out what compatibility really means )
