### ISSUE TITLE
Conan package manager integration

### ISSUE THREAD

**Issue by MatthieuMv** [nmoinvaz/minizip#458]
Hello Nathan,

First, I hope you and your family are safe in these sad days.. :(

I have to admit that I'm impressed of your contribution to a such standard library, that's huge !

I'm currently working on the refonte of a software that need zip decompression, and I'd love to use your library.
For portability purposes and sake of simplicity, I use conan as a C++ package manager and it'd be so nice to integrate minizip to it.

I can try to make a package myself if you don't want to, but as you have better knowledge of its build system, I prefer to ask you before.

Best regards,
Matthieu Moinvaziri

**Comment by nmoinvaz** [comment]
Thank you for your kind words. I hope your family is safe also! 

I have kind of paused accepting pull requests for package managers. There is an open pull request for swift package manager that I have not accepted. I like the idea of conan package manager more, because it is a C/C++ package manager and this library is C. The repository does already contain a Cocoapods package manager file and I almost wish I never accepted it. There are many package managers these days and I wonder if I will be adding package manager files for each of them in the future. The whole repository might be half consumed with package manager files - or at least that is my fear. So I am not sure what to do about it. 

I could add a package manager folder and store all the package manager files, but some package managers required their files to be in the root.

**Comment by MatthieuMv** [comment]
Conan is not that intrusive, it works by adding compilation instruction in an **another** repository to let anyone create a package for any project.
After more searching for non-official repositories, I've found people that already made it:
https://github.com/odant/conan-minizip https://bintray.com/elnoir/elnoir/nmoinvaz_minizip%3Aelnoir

I think my problem is solved, but your library definitely deserves to stay in the official conan repository to be used by anyone needing archive manipulation ^^
It's even more straightforward to use than other C++ high-level libs !

For now I'll try to find a working conan package, and I'll re-comment when done for anyone that could be interested.

Thank you !

**Comment by nmoinvaz** [comment]
I did some research and it appears that even Cocoapods specs can be submitted to package manager repository. So it might be similar for Conan. That is a great find that somebody already did it. I removed Cocoapods so I think all package managers should maintain their own files. Same like for Linux distributions their are package maintainers for those too.
