### ISSUE TITLE
Extracting uncompressed file from ZIP produces endless loop

### ISSUE THREAD

**Issue by zett42** [nmoinvaz/minizip#91]
Extracting uncompressed file with size < 65536 is OK.
Extracting uncompressed file with size == 65536 results in extracted file with size of 0.
Extracting uncompressed file with size >= 65537 produces an endless loop.

Can be reproduced with minizip master branch and current zlib version 1.2.11.

Test files:
[test65536.zip](https://github.com/nmoinvaz/minizip/files/803729/test65536.zip)
[test65537.zip](https://github.com/nmoinvaz/minizip/files/803730/test65537.zip)

**Comment by nmoinvaz** [comment]
This has been fixed. Thanks!

**Comment by zett42** [comment]
I can confirm that the issue no longer exists.
Thank you, much appreciated!

**Comment by puetzk** [comment]
Just commenting to link the issue to its commit and add some commentary, since it took me some hunting to find why my program was getting UNZ_PARAMERROR. The related change is fac878383c241f97df2598000cfadc5e4ee1065e, and it's not so much a fix for larger sizes, as forbidding one to even try.

zlib itself doesn't explicitly have such a limitation. The only reason sizes > 65535 don't work is because https://github.com/nmoinvaz/minizip/blob/5b7b3e5c4bf1ce8fd4d3da2057760972832a972f/unzip.c#L1305 is casting the avail_out value down to uint16_t. But I guess it's just being defensive; zlib's `uInt` is just `unsigned int`, and ANSI C89 would legally allow that to be a type with only [0,65535], even though most compilers nowadays would support up to 4GiB.

But on some old or unusual platform this defensiveness could be needed.

**Comment by nmoinvaz** [comment]
If somebody wants to submit a pull request against the 1.2 branch I will accept it.

**Comment by puetzk** [comment]
Yeah, I need to modernize this caller more someday, but the API changed a lot.

Why the complex check involving if (UINT_MAX == UINT16_MAX), instead of just if len > UINT_MAX? The latter would seem to express zlib's limitations on its own if the casts in minizip are gone...

**Comment by nmoinvaz** [comment]
It is a quick check to see if uint on the platform is 16 bit. 

Here is some backstory:

https://github.com/nmoinvaz/minizip/issues/201
https://github.com/nmoinvaz/minizip/pull/228/commits/3064a0e5519ddd360d104b45964c734b2b5ec5cb

**Comment by puetzk** [comment]
> It is a quick check to see if uint on the platform is 16 bit.

Right, but in 930f9188a5fb39947812d21306c6ae587fbe7c66 you went back to the cast being (uInt). With that instead of `(uint32_t)` or `(uint16_t)` you didn't explicitly need to know if that was 16- or 32-bit, you just needed to make sure the cast wouldn't overflow `(uInt)`, i.e. UINT_MAX.

Thanks for the backstory, #327 seems good on my end if it looks good to you.

**Comment by nmoinvaz** [comment]
It may have been a mistake. I don't think the bad casting exists in the master branch anymore. Thanks for the pull request.
